package bean;

public class Subject {

}

//SELECT  STUDENT.ENT_YEAR ,  STUDENT.CLASS_NUM ,  STUDENT.NO ,  STUDENT.NAME ,TEST.POINT , TEST.SUBJECT_CD
//FROM STUDENT
//JOIN  TEST
//ON STUDENT.CLASS_NUM = TEST.CLASS_NUM

//SELECT STUDENT.ENT_YEAR, STUDENT.CLASS_NUM, TEST.STUDENT_NO, STUDENT.NAME, TEST.POINT, TEST.SUBJECT_CD 
//FROM STUDENT
//JOIN TEST
//ON STUDENT.CLASS_NUM = TEST.CLASS_NUM
//AND STUDENT.NO = TEST.STUDENT_NO
//JOIN SUBJECT
//ON 
